### ISSUE TITLE
Confirming

### ISSUE THREAD

**Issue by AdamSC1-ddg** [kinecosystem/core#20]
@oryband - Currently building out things for the Kin ecosystem, I wanted to confirm that kinecosystem/core and kinecosystem/go (the go mono-repo) are the current Kin3 blockchain tools and I should assume that any features within those are ones that are intended to be supported and usable in the Kin Ecosystem?

**Comment by oryband** [comment]
Hey @AdamSC1-ddg 

The repositories https://github.com/kinecosystem/core/ and https://github.com/kinecosystem/go/ are forks of https://github.com/stellar/stellar-core and https://github.com/stellar/go respectively, and thus contain legacy code inherited from them. Please do not jump to any conclusions or assume anything.

In addition, please use these repos for the purposes of submitting PRs and reporting issues related to the applications themselves. You should use our community channels for discussions on any other topic such as the asked here.

**Comment by oryband** [comment]
Hey @AdamSC1-ddg , please note I edited the reply above and added more information.
